version: '3'

services:
  nestjs-app:
    container_name: nestjs-app
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=db  # MySQL host
      - MYSQL_USER=root  # MySQL username
      - MYSQL_PASSWORD=admin1243  # MySQL password
      - MYSQL_DATABASE=mydatabase  # MySQL database name
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:prod

  db:
    image: mysql:8.0.36  # Use MySQL version 8.0.36
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: blockchain_db  # Database name
      MYSQL_USER: root  # Username
      MYSQL_PASSWORD: admin123  # Password
      MYSQL_ROOT_PASSWORD: admin1243  # Root password
    ports:
      - "3306:3306"  # Expose MySQL port
    volumes:
      - db-data:/var/lib/mysql  # Persist MySQL data

volumes:
  db-data:  # Named volume for MySQL data
